# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "57fcbe52a4ccb6cf6751d94fbaea7002"
name = "Aarla Promotions"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://example.com/apps/aarla-promotions"
subpath = "aarla-promotions"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
